### ISSUE TITLE
[BUG] mapped keys doesn't make sense

### ISSUE THREAD

**Issue by ptxmac** [JohannesKlauss/react-hotkeys-hook#1006]
part of the `parseHotKey` use this map to replace certain symbols with string names: https://github.com/JohannesKlauss/react-hotkeys-hook/blob/main/src/parseHotkeys.ts#L5

But a few of them makes no sense at all:
```
  '-': 'slash',
  '#': 'backslash',
  '+': 'bracketright',
```

Are these typos, or is something weird happening in the downstream hotkeys library that remaps minus to slash?

**Comment by JohannesKlauss** [comment]
Since version 4 there is no downstream hotkeys library anymore. This is due to the fact that different keyboard layouts and languages have different keys for the underlying keycode.
This is an issue that I am not sure on how to fix. Listening only for `e.key` is not sufficient as I explained here:
[`https://github.com/JohannesKlauss/react-hotkeys-hook/issues/909#issuecomment-1407362756`](https://github.com/JohannesKlauss/react-hotkeys-hook/issues/909#issuecomment-1407362756)

Listening for keyCode on the other hand does not allow for a nice API like listening for `shift+-`, because `-` is not a valid `e.keyCode`, but a `e.key`.

If anyone has any input on solving this issue, I would highly appreciate it.
