### ISSUE TITLE
Best practice for curried handlers?

### ISSUE THREAD

**Issue by kwhitaker** [JohannesKlauss/react-hotkeys-hook#114]
I have a set of handler functions that look like this:

```
  const handler = foo => evt => {
    evt.preventDefault();
    doSomethingWithFoo(foo);
  };
```

If I use this as a callback for `useHotkeys`, the hotkey is going to reset every render, because the callback will change. For example:

```
useHotkeys('space', handler('bar'))
```

Is there a best practice I should be using to handle this kind of case?

Thanks!

**Comment by JohannesKlauss** [comment]
Digging into this I just realized that in most cases hotkeys will reset, because I guess most people will just insert an anonymous function, that gets recreated every time.

The solution is to memo the callback. But this is a bigger issue because the Hook itself seems not be capable of memoing a given callback, since it has no dependencies to work with. It's either resetting every render or memo the callback without deps and then the handler won't update even when the callback function changes.

For now I suggest for your case doing this:

```javascript
const handler = foo => useMemo(() => evt => {
  evt.preventDefault();
  doSomethingWithFoo(foo);
}, [foo]);

useHotkeys('space', handler('bar'))
```

This will prevent the resetting.
But nonetheless this memoing would need to be handled by the user in every case. Right now I don't see a good solution for this.

**Comment by kwhitaker** [comment]
@JohannesKlauss thanks for the quick response! I'll implement the pattern you've described.
