### ISSUE TITLE
Research: Find a way to memo callback

### ISSUE THREAD

**Issue by JohannesKlauss** [JohannesKlauss/react-hotkeys-hook#115]
When the callback gets passed by a anon function, it will be recreated every time, thus the reference will be gone and useEffect will be called on every render. Find a way to memo the callback within the hook.

**Comment by JohannesKlauss** [comment]
Fixed in v1.5.0

**Comment by retarsis** [comment]
@JohannesKlauss unfortunately, that solution doesn't work for me.

I think it's a fault of developer that passes a new reference of the callback on each re-render.
at least it will work, but not optimal,  and in my case it just doesn't work at all.

**The context**: my components accepts `selectedItem` prop and right in this component I register `useHotkeys` where I select `next` based on `selectedItem` value, but it always the same because of wrong memoization inside `useHotkeys`.

You may say that I should register `useHotkeys` in the parent components where I store the state, but it's almost impossible in the architecture of my project.

I just want to say that this solution makes some other approaches in the development of react components impossible which is frustrating 😞

I can help with PR and documentation but not sure if you agree

**Comment by JohannesKlauss** [comment]
@retarsis In which way is the memoisation "wrong"?
If you can create a minimal reproduction of your problem I am happy to discuss and help you with that. I am sure that there will be a solution to this :)
