### ISSUE TITLE
hotkeys in input

### ISSUE THREAD

**Issue by brietsparks** [JohannesKlauss/react-hotkeys-hook#127]
Is there a way to handle a hotkey press inside an text input?

relevant: https://github.com/jaywcjlove/hotkeys/issues/85#issuecomment-514387269

**Comment by JohannesKlauss** [comment]
I'll investigate this and come back to you.

**Comment by JohannesKlauss** [comment]
Well since the hook is just a wrapper function and the solution according to your linked issue is to use `hotkeys.filter` you could just use that. I am not quite sure how a working example would look like, since I don't quite understand the usage of `hotkeys.filter` in the mentioned issue.
Can you provide any more info on what the feature would look like to you?

**Comment by JohannesKlauss** [comment]
@gagandeepgill pls reference this comment https://github.com/JohannesKlauss/react-hotkeys-hook/pull/146#issuecomment-525041373
I think that we should make a parameter out of this, because otherwise it will be activated by default, which I don't think is expected behavior for users.

**Comment by Nolux** [comment]
Any updates on this? This is such a nice Hook

**Comment by JohannesKlauss** [comment]
@Nolux Sorry for not having any updates on this. Because of health issues I was forced to lay down programming for a bit. I try to get this done next week.

**Comment by Nolux** [comment]
No worries mate. I solved it using the hook mentioned above

**Comment by amitsetty** [comment]
Thanks for taking time out to update this. This hook is really helpful :)

**Comment by JohannesKlauss** [comment]
@Nolux This should already be possible. I'll update the docs on this.
