### ISSUE TITLE
Handling "?" key

### ISSUE THREAD

**Issue by deluan** [JohannesKlauss/react-hotkeys-hook#421]
I'm trying to add a HotKey for `?`. In my keyboard, `?` appears above `/` (common American layout). I was expecting this to work:
```
useHotkeys('?', callback)
```
But it didn't. The only way I was able to make it work was using:
```
useHotkeys('shift+/', callback)
```

The issue with this approach is that it is tied to the keyboard layout. In some layouts, the `?` is **not** on top of `/`, like in this one:
![unnamed](https://user-images.githubusercontent.com/331353/100560452-d45e8180-3283-11eb-9ffd-ce8658479860.png)

Is there a way to handle `?` independently of the keyboard layout? Thanks

**Comment by ianschmitz** [comment]
You probably want to file this over at https://github.com/jaywcjlove/hotkeys as this lib is just a wrapper of `hotkeys-js`.

**Comment by JohannesKlauss** [comment]
@ianschmitz  While this is true, it should be sufficient enough for @deluan  to listen for `shift+191`. The os should send the correct keyCode depending on the selected keyboard layout. `Shift+191` should always be question mark no matter what the keyboard layout is.

@deluan Pls check if that works and report back if there are any issues persisting.

**Comment by simon-scholz** [comment]
I actually have the same issue. Which means I can make it work with `useHotkeys('shift+/', callback)`, but this also doesn't work on Safari for some people.

I think the general approach of using the key code `191` (I think it's only `191`, without the `shift` in this case) is a good idea.

However I tried it in a few different ways and it doesn't seem to work. Maybe this has something to do with the keys prop only accepting strings? Because `hotkeys-js` has some examples, where the key code is used as a number type.

**Comment by JohannesKlauss** [comment]
I will check the typings.

**Comment by JohannesKlauss** [comment]
@deluan 
I just checked with a german keyboard layout. The `?` is reached via `shift+ß` but still only the hotkey combination `shift+/` works for me to get the question mark hotkey going. So the `/` character is tied to 191.

Just use `shift+/` as you done before and you should be fine, no matter the keyboard layout :)
