### ISSUE TITLE
How Would You Implement This Into A Class Component?

### ISSUE THREAD

**Issue by JoshuaKlaser** [JohannesKlauss/react-hotkeys-hook#503]
This is a great library and loving the ease of use with hooks. I am looking to perhaps use this library in an application that uses both class/functional components and have been trying to find a way to get this functionality into class components. What would be the method to get this working?

I have tried to create just a simple functional component that that contains a single useHotkeys, however the hotkey doesn't work when the component <Hotkey ...> is used in a class component.

```
import React from 'react';
import PropTypes from 'prop-types';
import { useHotkeys } from 'react-hotkeys-hook';

export default function Hotkey(props) {
  const {
    hotKey,
    callback,
  } = props;

  const localCallback = () => {
    callback();
  };

  useHotkeys(hotKey, localCallback, []);

  return null;
}

Hotkey.propTypes = {
  hotKey: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.array,
  ]).isRequired,
  callback: PropTypes.func.isRequired,
};
```

I have also tried to create a HigherOrderComponent, however since I'm not the greatest at react I kept having issues with getting that to work.

Cheers.

**Comment by JohannesKlauss** [comment]
"Doesn't work" is not a very specific description for the problem. What does not work? Does the callback get executed or not? Is the state inside the callback stale?

I am guessing that you are not embedding the component correctly or passing invalid props.
Here is a working example:
https://codesandbox.io/s/suspicious-cray-4cord

But since you are creating a functional component just to make the hotkeys work inside a class component you might want to consider this package that is built for class components:
https://github.com/jaywcjlove/react-hotkeys

**Comment by JoshuaKlaser** [comment]
Thanks for the reply. I apologise for not explaining my problem more clearly, as I was a bit rushed when I wrote the question. The original issue was that useHotkeys was not triggering at all when used from a class component (which is now resolved).

I had made the functional component above to have it used in class components, however no matter what I tried the callback just wouldn't trigger. It seemed really odd as the useHotkeys usage in other functional components worked so quickly and easily. I ended up with that largish component above as a result of trying different things to try and get it to work.

Using the smaller functional component you had in your first example I managed to get it working with no issues. Thankyou so much for getting back to me with an example. It has helped me learn on how to approach hooks for class components.
