### ISSUE TITLE
[Question]: How to prevent browser's default event?

### ISSUE THREAD

**Issue by Vinaxi07** [JohannesKlauss/react-hotkeys-hook#550]
I'm unable to prevent the browser's default event for `Ctrl + n`.

```
useHotkeys('ctrl+n', event => {
    setOpen(true)
    event.preventDefault()
  })
```

**Comment by JohannesKlauss** [comment]
What would the default behavior be for ctrl+n?

**Comment by Vinaxi07** [comment]
I've to open a new tab in the **chrome extension app** on press `Ctrl + n`.

**Comment by Nishchit14** [comment]
Here is the brief context @JohannesKlauss, It's a shortcut in our app, The shortcut `ctrl+n` should open a new tab within our app instead of the chrome (browser)'s tab.
![image](https://user-images.githubusercontent.com/5078921/121672223-2c94fc80-cacd-11eb-9e31-7802fac2a425.png)

**Comment by JohannesKlauss** [comment]
This is not possible.

`ctrl+t`, `ctrl+n` and `ctrl+w` are reserved shortcuts in chrome (and pretty sure Firefox and Safari as well). You cannot override them or prevent them from happening, since these are vital controls for the user.

Here is the corresponding chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=33056

**Comment by kermopajula** [comment]
I'm experiencing the same for `cmd+d` which adds a bookmark in Chrome, but I didn't find it mentioned in the Chromium bug you referenced. Is it the same thing or could this bookmark thing be prevented somehow?
