### ISSUE TITLE
Export hotkeys

### ISSUE THREAD

**Issue by codingedgar** [JohannesKlauss/react-hotkeys-hook#648]
Hi, amazing lib 💛

Is it possible to export `hotkeys`? seems kind of necessary specially to use with modifier keys

**Comment by JohannesKlauss** [comment]
Hi thanks for the kind words.

I am not sure if I get the use case you are referring to. Why is it necessary to export `hotkeys` (with that I guess you mean the underlying package) when using modifier keys. Could you elaborate on that?

In any case you can just add the `hotkeys-js` package to you package.json and use the package directly.

**Comment by codingedgar** [comment]
Honestly just to void doing this:

> In any case you can just add the `hotkeys-js` package to you package.json and use the package directly.

My use case is implementing `hotkeys-js` examples like this one:
https://github.com/jaywcjlove/hotkeys#api-reference
```
hotkeys('*', function() {
  if (hotkeys.shift) {
    console.log('shift is pressed!');
  }

  if (hotkeys.ctrl) {
    console.log('ctrl is pressed!');
  }

  if (hotkeys.alt) {
    console.log('alt is pressed!');
  }

  if (hotkeys.option) {
    console.log('option is pressed!');
  }

  if (hotkeys.control) {
    console.log('control is pressed!');
  }

  if (hotkeys.cmd) {
    console.log('cmd is pressed!');
  }

  if (hotkeys.command) {
    console.log('command is pressed!');
  }
});
```

**Comment by JohannesKlauss** [comment]
Hmh, I don't really get that use case, since this is just an example of the several modifier key checks.

If you want to check for modifier keys use could either use `isHotkeyPressed` or listen for it with `shift+a` for example. Do you have a more specific use case to illustrate a problem, that the hook doesn't cover in a sufficient way?

**Comment by codingedgar** [comment]
The use case exists becase some modifiers cannot be set (https://github.com/jaywcjlove/hotkeys/issues/206#issuecomment-652758711), therefore cannot be sole bound to a hotkey.

Further, as i'm trying to exemplify in https://github.com/JohannesKlauss/react-hotkeys-hook/issues/649 `isHotkeyPressed` is not reliable, and I could say it is reasanoble any `hotkey-js` usecase (specially a documented one) should be easely implemented.

May I ask what is wrong with re-exporting `hotkeys-js` or passing the instance down?

**Comment by JohannesKlauss** [comment]
hotkeys-js is not being re exported since (as I mentioned above) you can easily use the package by itself it you need to. Also Version 4 will drop hotkeys-js as its underlying dependency, so it would be an upcoming breaking change.

As mentioned in #649 if you provide an example that breaks `isHotkeyPressed` I am happy to try to fix it and then you don't need the hotkeys package reexported to check for modifier keys 🙂

**Comment by codingedgar** [comment]
Makes sense, I'll try to reproduce the issue in a code sandbox
