### ISSUE TITLE
[BUG] Previously working shortcuts broke in the switch from ctrl to meta on Mac Safari

### ISSUE THREAD

**Issue by warbrett** [JohannesKlauss/react-hotkeys-hook#900]
**Describe the bug**
`Meta+1` and 
`meta+shift+/` both stopped working after the upgrade from version 3 to the latest version 4. Previously these were both using "ctrl" rather than meta.

**To Reproduce**
on Mac OS safari try: https://codesandbox.io/s/affectionate-proskuriakova-mju5d9?file=/src/App.tsx

**Desktop (please complete the following information):**
 - MacOS
 - Safari
 - 16.2

**Additional context**
Thanks for all the great work

**Comment by JohannesKlauss** [comment]
This is all fixed in 4.3.3. To make `meta+shift+/` work you would have to specify the key you want `/` to live on. This is because different keyboard layouts have different modifiers or physical keys to enter `/`.

For example on a german keyboard layout `/` is reached via `shift+7`. On a US and UK layout it is its own key as far as I know.

So depending on your users keyboard layout the combination might vary.
